### ISSUE TITLE
Bulb response error: client quota exceeded (code -1)

### ISSUE THREAD

**Issue by callmenoodles** [Leixb/yeelight#10]
When you run a method more than 60 times a minute, it will trigger this error. I know that by turning on music mode, this should be resolved because it removes the rate limit. However, I have no idea how to use start_music(). What are the host and port?

Besides that, even if music mode is already turned on using the Yeelight mobile app, I still get rate limited.

This is also a partial fix for #4.

**Comment by PolyMeilex** [comment]
To qoute the api docs: 
```
When control device wants to start music mode, it needs start a TCP
server firstly and then call “set_music” command to let the device know the IP and Port of the
TCP listen socket. After received the command, LED device will try to connect the specified
peer address. If the TCP connection can be established successfully, then control device could
send all supported commands through this channel without limit to simulate any music effect.
The control device can stop music mode by explicitly send a stop command or just by closing
the socket.
```

This crate, as far as I can tell, does some heavy lifting in this regard, so you just have to set a random (unused) port, and the crate will setup TCP listener internally, the IP is just IP of your machine.

**Comment by Leixb** [comment]
> To qoute the api docs:
> 
> ```
> When control device wants to start music mode, it needs start a TCP
> server firstly and then call “set_music” command to let the device know the IP and Port of the
> TCP listen socket. After received the command, LED device will try to connect the specified
> peer address. If the TCP connection can be established successfully, then control device could
> send all supported commands through this channel without limit to simulate any music effect.
> The control device can stop music mode by explicitly send a stop command or just by closing
> the socket.
> ```
> 
> This crate, as far as I can tell, does some heavy lifting in this regard, so you just have to set a random (unused) port, and the crate will setup TCP listener internally, the IP is just IP of your machine.

That is correct.

A simple example should look like this:

```rust
let mut bulb = yeelight::Bulb::connect("<bulb address>", 0).await?;
let mut music_conn = bulb.start_music("<your machine address>", <random port>).await?;

music_conn.toggle().await?;
// Send requests through music_conn

// Once you are done, you can close the connection
drop(music_conn);
```

> Besides that, even if music mode is already turned on using the Yeelight mobile app, I still get rate limited.

AFAIK the music mode in the app works with the same principle, it creates a TCP connection between the phone and the bulb in which the app sends the requests. It does not affect other devices connecting to the bulb.

**Comment by callmenoodles** [comment]
Thanks to @PolyMeilex, I tried something like that but when I run this for example:
`let mut music_conn = bulb.start_music("192.168.2.12", 3333).await?;`

It gives me:
> Error: Response(-5001, "invalid params")

**Comment by Leixb** [comment]
@callmenoodles can you try to run the newest code from the master branch? I have made some changes. (You don't need to provide the port anymore). I also added an example in `examples/music.rs`

If that does not work, you can try to send the payload with `netcat` or `telnet` and check what is the response of the lamp.


In Linux / macOS you can do something like this:

In one terminal (make sure this runs first):
```bash
echo -ne '{"id":1,"method":"toggle","params":[]}\r\n' | nc -l 12345 -w1
```

On a second one:
```bash
echo -ne '{"id":1,"method":"set_music","params":[1,"<computer IP>",12345]}\r\n' | nc -w1 <lamp IP> 55443
```

**Comment by callmenoodles** [comment]
Thanks for the quick responses! The updated master branch works as long as you use a 1.X version of Tokio. @Leixb Would you mind updating the crate as well?
