### ISSUE TITLE
TCP connection never established in `start_music`

### ISSUE THREAD

**Issue by callmenoodles** [Leixb/yeelight#13]
Music mode works on my machine in Arch Linux, but on Windows 10, I tried adding some debug statements to the library and found out it keeps hanging on `let (socket, _) = listener.accept().await?;` in `src/lib.rs` in `Bulb::start_music` For more details have a look at [my project](https://github.com/callmenoodles/ambeelight).

Here is my output of Wireshark after running my project:
https://ibb.co/1bmM72Q

`192.168.2.6` is my lamp, the other is the host

**Comment by Leixb** [comment]
Have you tried disabling Windows Firewall or adding an exception rule for your application?

**Comment by callmenoodles** [comment]
> Have you tried disabling Windows Firewall or adding an exception rule for your application?

Yes, both.

**Comment by Leixb** [comment]
@callmenoodles can you try the code from #14 ? I don't have any Windows machine available to test the code right now.

**Comment by callmenoodles** [comment]
You're a genius.
