### ISSUE TITLE
get bright shows 100 if the bulb is off

### ISSUE THREAD

**Issue by rp1231** [Leixb/yeelight#17]
The get bright command outputs 100 if the bulb is off.

**Comment by Leixb** [comment]
That's how the [yeelight API](
https://www.yeelight.com/download/Yeelight_Inter-Operation_Spec.pdf) works, this is simply a wrapper around it. Their rationale is probably that you may want to check the brightness of the light without having to turning it on.

You should check `power` to check if the light is on or off. You can do it in a single call with: `get power bright` and the results will be in separate lines like so:
```shell
$ yeelight <MY_BULB> get power bright
off
40
```
