### ISSUE TITLE
Is there any way to set the music mode via the cli?

### ISSUE THREAD

**Issue by rp1231** [Leixb/yeelight#18]
I've made a ui which utilizes the cli as the backend utilizing the tauri framework.
And I get rate limited sometimes.
Is there any way to set the music mode via the cli?
I'm new to programming so I don't know how to use the library as yet.
Thanks

**Comment by Leixb** [comment]
@rp1231 You should use the State manager in Tauri to keep the bulb connection open. I'm not familiar with Tauri but I think that having a `Mutex<Bulb>` in your state is what you will need. [The examples in Tauri my help](https://docs.rs/tauri/latest/tauri/trait.Manager.html#mutability), they show how to use a database connection, a connection with a lightbulb is similar.

Regarding the music mode, once you have a working implementation with normal commands, you can use `start_music("<your computer ip>")` to get a connection in music mode, then you just send the commands as normal to this new connection. The only difference is that you will get no response. Something like this:

```rust
let mut bulb = Bulb::connect(my_bulb_ip, 0).await?;
let mut music_conn = bulb.start_music(my_computer_ip).await?;

music_conn.set_power(Power::On, Effect::Sudden, no_duration, Mode::Normal).await?;
```

Either bulb or music_conn should be part of your state, and in your Tauri command, you take the state and send the commands. This way, you don't create new connections (You may need to handle disconnects from the light bulb, but this is an entirely different matter).
